import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "AI Usage Disclaimer â€” EternalNotes",
  description: "AI Usage Disclaimer for EternalNotes",
};

export default function AiDisclaimerPage() {
  return (
    <article className="prose-legal">
      <h1>AI Usage Disclaimer</h1>
      <p className="meta">Last updated: 11 May 2026</p>

      <p>
        EternalNotes uses artificial intelligence to help you retrieve, summarise, quiz, and
        study your own documents. This page explains how AI is used, its limitations, and
        your responsibilities when using AI-powered features.
      </p>

      <h2>1. How AI Works in EternalNotes</h2>
      <p>
        EternalNotes uses a technique called <strong>Retrieval-Augmented Generation (RAG)</strong>.
        When you ask a question, the system searches your indexed notes and documents for
        relevant passages, then uses an AI language model to compose an answer based on what
        it found. This means AI responses are grounded in your own content â€” not the open
        internet.
      </p>

      <h2>2. AI Can Make Mistakes</h2>
      <p>
        AI language models can produce incorrect, incomplete, or misleading outputs even when
        working from accurate source material. This is sometimes called "hallucination." You
        should:
      </p>
      <ul>
        <li>Treat AI-generated answers as a starting point, not a definitive source</li>
        <li>Cross-check important information against the original source documents</li>
        <li>Not rely solely on AI outputs for decisions that matter</li>
      </ul>

      <h2>3. Not Professional Advice</h2>
      <p>
        Nothing generated by EternalNotes's AI tools constitutes professional advice of any
        kind, including:
      </p>
      <ul>
        <li><strong>Legal advice</strong> â€” AI summaries of legal documents are not a substitute for a lawyer</li>
        <li><strong>Medical advice</strong> â€” AI outputs about health topics are not a substitute for a doctor</li>
        <li><strong>Financial advice</strong> â€” AI summaries of financial content are not investment guidance</li>
        <li><strong>Academic advice</strong> â€” AI-generated study content should not replace thorough study</li>
      </ul>
      <p>
        You remain responsible for all decisions you make based on information from the platform.
      </p>

      <h2>4. AI Providers and Data</h2>
      <p>
        Depending on how EternalNotes is configured, AI processing may occur:
      </p>
      <ul>
        <li>
          <strong>Locally via Ollama</strong> â€” all processing happens on the server, nothing
          is sent externally
        </li>
        <li>
          <strong>Via OpenAI (your own key or a hosted key)</strong> â€” relevant excerpts from
          your documents and your query text are sent to OpenAI's API to generate a response.
          OpenAI's usage policies and privacy practices apply.
        </li>
      </ul>
      <p>
        We do not use your content to train AI models.
      </p>

      <h2>5. AI-Generated Quizzes and Flashcards</h2>
      <p>
        Quizzes and flashcards generated by EternalNotes are created from your own notes.
        They may contain errors if the source material contains errors, or if the AI
        misinterprets the content. Always review generated study materials before relying on them.
      </p>

      <h2>6. No Guarantee of Accuracy</h2>
      <p>
        EternalNotes makes no warranty, express or implied, regarding the accuracy, completeness,
        or reliability of any AI-generated content. Use of AI features is at your own discretion
        and risk.
      </p>

      <h2>7. Responsible Use</h2>
      <p>
        Do not use AI features to generate content intended to deceive, harm, or violate the
        rights of others. See our <a href="/legal/acceptable-use">Acceptable Use Policy</a> for
        full details.
      </p>

      <h2>8. Questions</h2>
      <p>
        Questions about how AI is used in EternalNotes? Contact us at{" "}
        <a href="mailto:discordboteternal@gmail.com">discordboteternal@gmail.com</a> or
        via <a href="https://discord.gg/6hhxtpzkAE" target="_blank" rel="noopener noreferrer">Discord</a>.
      </p>
    </article>
  );
}

